#                                                                        #
# Default subroutes configuration for the Neos.Seo package         #
#                                                                        #

# Make sure to include the following commented route before the Neos.Neos subroutes in your global /Configuration/Routes.yaml

##
# Neos Seo: XML Sitemap

#-
#  name: 'Neos Seo'
#  uriPattern: '<NeosSeoSubroutes>'
#  subRoutes:
#    'NeosSeoSubroutes':
#      package: 'Neos.Seo'
#      variables:
#        'xmlSitemapPath': 'sitemap.xml'

##
# XML Sitemap

-
  name:  'XML Sitemap'
  uriPattern: '{node}<xmlSitemapPath>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'xml.sitemap'
  routeParts:
    'node':
      handler:     'Neos\Neos\Routing\FrontendNodeRoutePartHandlerInterface'
      options:
        onlyMatchSiteNodes: TRUE
  appendExceedingArguments: TRUE
